export const CAROUSEL_REQUEST = 'carousel_request'
export const CAROUSEL_RECEIVE = 'carousel_receive'
export const CAROUSEL_FAIL = 'carousel_fail'
export const SWEET_SHOW_REQUEST = 'sweet_show_request'
export const SWEET_SHOW_RECEIVE = 'sweet_show_receive'
export const SWEET_SHOW_FAIL = 'sweet_show_fail'
